services:
  spotify-scraper:
    container_name: spotify-scraper
    image : "ghcr.io/hadebot-devs/spotifyscraper:"
    restart : "no"  
    ports:
      - "127.0.0.1:8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/token"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  
      