
name: Ruff - Python Code Quality and Formatting
on: [push, pull_request]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install ruff
        run: pip install ruff

      - name: Check code with ruff
        run: ruff check -v --fix

      - name: Format code with ruff
        run: ruff format -v
      
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automatically format Python code with ruff" || echo "No changes to commit"
          git push